### ISSUE TITLE
The processing of the nc files should happen once.

### ISSUE THREAD

**Issue by SimonGoring** [PalEON-Project/Shiny#4]
Right now in the code every time `server.R` is loaded (i.e., every time someone comes to the webpage) we open the netCDF files, pull all the variables, average the posteriors and get the standard deviations.  This will make the page extremely slow.

I think that there needs to be a file called something like `clean_nc.R` in the R folder that does all this and exports to a RDS file (an R save file) so that we have a single big `data.frame` with x, y and taxon mean and sd for each of the taxa across the domain.  Then all we have to do is load the file once on startup and `subset` it when we want to plot.  This will save an enormous amount of time.

**Comment by jpeters7** [comment]
Yes!!  Thank you for reminding me of this. Michelle was having trouble with the netcd processing being slow and Chris had made a suggestion about just saving the output. However, Michelle wasn't able to get the code to work before she left. 
Your outline of the process sounds good, but I don't know how to write to code to implement it. If you or Chris (when he is back from hiking) could work on it that will move this along faster.  If you guys don't have time, I'll add it to my To Do list and will bash away at it.

**Comment by paciorek** [comment]
Something like this should work. You'll need to monkey with it to make a
list or some such  I'm not sure if you want a matrix with row = x and
column = y (or vice versa), or a data frame with x and y as columns. Also
note that this saves the output as a ncdf rather than R binary format.
Either should be fine and should load quickly once you've done the
summarization that calculates the means/sds.

Simon, not sure why you are suggesting RDS file instead of simply an R Data
(.Rda/.RData) file.

Jody, let me know if you need more detail - the code below has some but
also is something of a sketch.

library(ncdf4)

inputNcdfPtr <- nc_open(file.path(outputDir, inputNcdfName))

# this uses a function from the stat composition code - let me know if you

have trouble getting it

# you don't need this business about creating the output ncdf files if you

save to an R data file
makeAlbersNetCDFsummary(name = 'proportion posterior mean', units =
'unitless (proportion from 0 to 1)', longname = 'posterior mean of relative
composition, relative to all tree taxa,', fn = pmNcdfName, dir = outputDir,
dims = inputNcdfPtr$dim[1:2], taxa = taxa)
makeAlbersNetCDFsummary(name = 'proportion posterior standard deviation',
units = 'unitless (standard deviation of proportions', longname =
'posterior standard deviation of relative composition, relative to all tree
taxa,', fn = psdNcdfName, dir = outputDir, dims = inputNcdfPtr$dim[1:2],
taxa = taxa)

pmNcdfPtr <- nc_open(file.path(outputDir, pmNcdfName), write = TRUE)
psdNcdfPtr <- nc_open(file.path(outputDir, psdNcdfName), write = TRUE)

# pm <- list()  # if saving to Rda file

for(v in taxa) {
    dat <- ncvar_get(inputNcdfPtr, v, c(1, 1, 1), c(-1, -1, -1))
    pm <- apply(dat, c(1, 2), mean)  # or pm[[v]] <- apply(dat, c(1,2),
mean)  # if saving to Rda file
    psd <- apply(dat, c(1, 2), sd)
    # could add other summaries here, e.g. 2.5 and 97.5%iles for
uncertainty intervals, using quantile()
    ncvar_put(pmNcdfPtr, v, pm, start = c(1, 1), count = c(-1, -1))
    ncvar_put(psdNcdfPtr, v, psd, start = c(1, 1), count = c(-1, -1))
}

# or save as R binary format

# save(pm, psd, file = 'blah.Rda')

**Comment by SimonGoring** [comment]
I think everything works now.  Jody one issue I had (and I'm not sure if I
pushed the commit) is that the ui.R reference to the taxonomy names
requires that the RDS file be loaded as it is in the server file.
Apparently the two of
es don't 'talk' to each other.

Chris, Gavin Simpson has a good post about why he uses RDS, I'll try to dig
it up, but I'm on my way out to play with the kids.

**Comment by SimonGoring** [comment]
FYI @paciorek here's the article by Gavin Simpson about RDS files: http://www.fromthebottomoftheheap.net/2012/04/01/saving-and-loading-r-objects/

I'm closing this now, and will re-open one about preloading shapefiles separately.
